export const companies = [
	{
		src: "/company/blurb.png",
		name: "GoVertical",
		position: "Software Engineer",
		started: "May 2022",
		ended: "Sept 2023",
		techSrc: [
			"/tech/aws.png",
			"/tech/docker.png",
			"/tech/firebase.png",
			"/tech/gcp.png",
			"/tech/reactjs.png",
			"/tech/typescript.png",
			"/tech/git.png",
		],
		points: [
			"Chron jobs to manage timely functions through a combination of pub/sub methods and HTTP.",
			"Assisted in developing the company's Continuous Integration/Deployment pipeline, ensuring faster and safer code deployment.",
			"Drove the development of several robust and scalable APIs and cloud functions using Node.js and Python, demonstrating proficiency in serverless and Dockerized environments.",
			"Operated effectively in a startup/fast-paced environment, managing, and deploying web applications leveraging React and Next.js.",
			"Created and managed Virtual Machine instances on Google Cloud Platform to deploy and scale services, optimizing infrastructure for performance and cost-efficiency.",
		],
	},
	{
		src: "/company/holmetrics.png",
		name: "Holmetrics",
		position: "Full-Stack Developer Intern",
		started: "May 2021",
		ended: "Jan 2022",
		techSrc: [
			"/tech/aws.png",
			"/tech/mysql.png",
			"/tech/firebase.png",
			"/tech/tailwind.png",
			"/tech/reactjs.png",
			"/tech/typescript.png",
			"/tech/git.png",
		],
		points: [
			"Engineered a responsive and user-friendly dashboard using ReactJs, ensuring a seamless user experience. The design was enhanced with the modern aesthetics of the TailwindCSS framework.",
			"Integrated a MySQL database to store and manage vast amounts of data, ensuring efficient data retrieval and optimal performance.",
			"Incorporated Okta for robust and secure user authentication, ensuring data privacy and safeguarding user credentials.",
			"Integrated leading business intelligence platforms, Tableau and GoodData, to visualize complex metrics. This provided users with clear, actionable insights.",
			"Deployed the application on AWS EC2, ensuring high availability, scalability, and optimal performance for users worldwide.",
		],
	},
	{
		src: "/company/uofc.png",
		name: "University Of Calgary",
		position: "Full-Stack Developer",
		started: "Oct 2020",
		ended: "Sept 2022",
		techSrc: [
			"/tech/docker.png",
			"/tech/mysql.png",
			"/tech/redux.png",
			"/tech/git.png",
			"/tech/reactjs.png",
			"/tech/typescript.png",
		],
		points: [
			"Collaborated with a research team to optimize a dynamic visualizer by transitioning from SVG to Canvas, achieving a reduction in load times from 10 seconds to 2 seconds for 200k+ data points.",
			"Developed an interactive interface using ReactJS and D3.js, enhancing user experience with features like filters, drill downs, and zoom/pan capabilities, enabling tailored data insights.",
			"Set up and manage a robust back-end using Express.js and PostgreSQL, allowing users to upload their own custom CSV data file, which can later be loaded into the visualizer in a seamless flow and operation.",
			"Adopted a bi-weekly sprint cycle, facilitating regular feedback and iterative improvements. This approach ensured timely delivery of features and alignment with the researcher's requirements.",
			"Leveraged Docker to containerize the application, ensuring consistent environments across development, testing, and production stages. This streamlined deployment processes and enhanced application scalability.",
		],
	},
];
